package:
  name: tomopy
  version: '0.0.9'

source:
  git_url: https://github.com/dgursoy/tomopy.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - h5py
    - scikit-image
    - pywavelets
    - tifffile

test:
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.io
    - tomopy.io.data
    - tomopy.io.phantom
    - tomopy.io.recipes
    - tomopy.prep
    - tomopy.recon

about:
  home: http://tomopy.readthedocs.org
  license: BSD
  summary: 'X-ray imaging toolbox'
