package:
  name: tomopy
  version: '1.1.4'

source:
  git_url: https://github.com/tomopy/tomopy.git

  
build:
  number: 0

requirements:
  build:
    - mkl-devel
    - python
    - setuptools
    - m2w64-gcc # [win]

  run:
    - python
    - numpy
    - h5py
    - scipy
    - six
    - scikit-image
    - pywavelets
    - mkl
    - mkl_fft
    - dxchange
    - numexpr
    - futures # [py2k]
    - m2w64-gcc-libs # [win]
    
test:
  # Python imports
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.misc.corr
    - tomopy.misc.morph
    - tomopy.misc.phantom
    - tomopy.prep
    - tomopy.prep.alignment
    - tomopy.prep.normalize
    - tomopy.prep.phase
    - tomopy.prep.stripe
    - tomopy.recon
    - tomopy.recon.algorithm
    - tomopy.recon.rotation
    - tomopy.recon.vector
    - tomopy.util
    - tomopy.util.dtype
    - tomopy.util.extern
    - tomopy.util.mproc

about:
  home: http://tomopy.readthedocs.org
  license: BSD-3
  summary: 'Tomographic reconstruction in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

