package:
  name: tomopy
  version: '1.0.0'

source:
  git_url: https://github.com/dgursoy/tomopy.git
  
build:
  number: 0

  script_env:
   - LD_LIBRARY_PATH
   - C_INCLUDE_PATH

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - six
    - scikit-image
    - pywavelets
    - pyfftw
    - dxchange
    - numexpr
    - futures # [py2k]
    
test:
  # Python imports
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.misc.corr
    - tomopy.misc.morph
    - tomopy.misc.phantom
    - tomopy.prep
    - tomopy.prep.normalize
    - tomopy.prep.phase
    - tomopy.prep.stripe
    - tomopy.recon
    - tomopy.recon.algorithm
    - tomopy.recon.rotation
    - tomopy.util
    - tomopy.util.dtype
    - tomopy.util.extern
    - tomopy.util.mproc

about:
  home: http://tomopy.readthedocs.org
  license: BSD-3
  summary: 'Tomographic reconstruction in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

