package:
  name: tomopy
  version: '0.1.5'

source:
  git_url: https://github.com/dgursoy/tomopy.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - h5py
    - scikit-image
    - pywavelets
    - netcdf4
    - spefile
    - edffile
    - tifffile

test:
  # Python imports
  imports:
    - tomopy
    - tomopy.io
    - tomopy.io.reader
    - tomopy.io.writer
    - tomopy.io.exchange
    - tomopy.io.phantom
    - tomopy.misc.corr
    - tomopy.misc.mask
    - tomopy.misc.morph
    - tomopy.misc.mproc
    - tomopy.prep.normalize
    - tomopy.prep.phase
    - tomopy.prep.stripe
    - tomopy.recon.algorithm
    - tomopy.recon.rotation

about:
  home: http://tomopy.readthedocs.org
  license: BSD-3
  summary: 'Tomographic reconstruction in Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
