package:
  name: tomopy
  version: '1.1.4'

source:
  # git_url: https://github.com/tomopy/tomopy.git
  path: .

build:
  number: 1
  script:
    - "{{ PYTHON }} build.py"
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - mkl-devel  # [not win]
  host:
    - Make  # [win]
    - MinGW  # [win]
    - mkl-devel
    - pip
    - python={{ python }}
    - setuptools
  run:
    - dxchange
    - futures  # [py2k]
    - numexpr
    - mkl
    - mkl_fft
    - python={{ python }}
    - pywavelets
    - numpy
    - scikit-image
    - scipy
    - six

test:
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - nosetests test

app:
    own_environment: True

about:
    home: http://tomopy.readthedocs.io
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Tomographic reconstruction in Python.'
