[build-system]
requires = [
  "cmake",
  "ninja; platform_system!='Windows'",
  "scikit-build>=10.1",
  "setuptools>=45",
  "setuptools_scm>=6.2",
  "setuptools_scm_git_archive",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
