# tomopy makefile for Mac OS

include Mk.config

CC_WARNINGS  = -Wno-unused-result -Wsign-compare -Wunreachable-code -Wall -Wstrict-prototypes
CC_OPTIMIZE  = -DNDEBUG -g -fwrapv -O3
CC           = $(COMPILER_DIR) $(CC_OPTIMIZE) $(CC_WARNINGS) $(ARCH_TARGET) $(INCLUDE) \
                -DUSE_MKL -std=c99 $(CFLAGS)
LINK         = $(COMPILER_DIR) -bundle -undefined dynamic_lookup $(ARCH_TARGS) $(LINK_LIB) $(LDFLAGS)

include Mk.base
