# tomopy makefile for Linux

include Mk.config

CC_WARNINGS  = -Wl,--sysroot=/ -Wsign-compare -Wall -Wstrict-prototypes
CC_OPTIMIZE  = -DNDEBUG -g -fwrapv -O3 -fPIC -fopenmp
CC           = $(COMPILER_DIR) -pthread $(CONDA_COMPAT)  $(CC_OPTIMIZE) $(CC_WARNINGS) $(ARCH_TARGET) $(INCLUDE) -DUSE_MKL -std=c99
LINK         = $(COMPILER_DIR) -pthread -shared $(CONDA_COMPAT) $(LINK_LIB) -Wl,-rpath=$(LINK_LIB)  -Wl,--no-as-needed -Wl,--sysroot=/

include Mk.base
