################################################################################
#   Build stage 1
################################################################################
ARG TAG=latest
FROM jrmadsen/tomopy-blue-waters:${TAG} as builder

WORKDIR /root
USER root
ENV HOME /root
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US
ENV LC_ALL C
ENV SHELL /bin/bash
ENV BASH_ENV /etc/bash.bashrc
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /work

#------------------------------------------------------------------------------#
#   packages
#------------------------------------------------------------------------------#
COPY ./.docker/apt.sh /work/apt.sh
RUN ./apt.sh

#------------------------------------------------------------------------------#
#   conda installation
#------------------------------------------------------------------------------#
ARG PYTHON_VERSION=3.6
ENV PYTHON_VERSION ${PYTHON_VERSION}

COPY ./.docker/conda.sh /work/conda.sh
RUN ./conda.sh

#------------------------------------------------------------------------------#
#   remove junk
#------------------------------------------------------------------------------#
COPY ./.docker/cleanup.sh /work/cleanup.sh
RUN ./cleanup.sh

#------------------------------------------------------------------------------#
#   library path fixes
#------------------------------------------------------------------------------#
COPY ./.docker/config-path.sh /work/config-path.sh
RUN ./config-path.sh

#------------------------------------------------------------------------------#
#   install PGI compiler
#------------------------------------------------------------------------------#
ENV PGI_ACCEPT_EULA accept
ENV PGI_SILENT true
COPY ./.docker/pgilinux-2018-184-x86-64.tar.gz /work/pgi/

RUN cd /work/pgi && \
    tar -xzf pgilinux-2018-184-x86-64.tar.gz && \
    ./install

#------------------------------------------------------------------------------#
#   remove everything from work
#------------------------------------------------------------------------------#
RUN rm -rf /work/*

COPY ./.docker/runtime-entrypoint.sh /cuda-runtime-entrypoint.sh

################################################################################
#   Build stage 2
################################################################################
FROM scratch

WORKDIR /root
USER root
ENV HOME /root
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US
ENV LC_ALL C
ENV SHELL /bin/bash
ENV BASH_ENV /etc/bash.bashrc

WORKDIR /home

COPY --from=builder / /

SHELL [ "/bin/bash", "--login", "-c" ]
ENTRYPOINT [ "/cuda-runtime-entrypoint.sh" ]
