# configure system-specifc settings for tomopy Makefiles
#
# writes systems-dependent Mk.config file

from sys import prefix, platform
from os import listdir
from os.path import join as pjoin
from os.path import isdir
import shutil
import time

class Config:
    def __init__(self):
        self.sharedlib = ''
        self.arch_target = ''
        self.link_libs = ''
        self.include = ''
        top_include = pjoin(prefix, 'include')

        includes = ['-I%s' % (top_include)]
        for fname in listdir(top_include):
            tdir = pjoin(top_include, fname)
            if isdir(tdir) and  'python' in fname:
                includes.append('-I%s' % tdir)

        self.link_libs = '-L%s' % pjoin(prefix, 'lib')
        self.include = '%s' % (' '.join(includes))

    def format(self):
        buff = ['#### autogenerated %s' % time.ctime(),
                'SHAREDLIB    = %s' % self.sharedlib,
                'ARCH_TARGET  = %s' % self.arch_target,
                'LINK_LIBS    = %s' % self.link_libs,
                'INCLUDE      = %s' % self.include,
                '####', '']

        return '\n'.join(buff)


def config_linux():
    """ config for Linux"""
    config = Config()
    config.sharedlib = 'libtomopy.so'
    return config.format()

def config_macos():
    """ config for MacOS"""
    config = Config()
    config.sharedlib = 'libtomopy.dylib'
    config.arch_target = '-arch x86_64'
    return config.format()

def config_windows():
    """ config for Windows"""
    """ config for Linux"""
    config = Config()
    config.sharedlib = 'tomopy.dll'
    return config.format()

config = None
if platform.lower().startswith('win'):
    shutil.copy('Makefile.windows', 'Makefile')
    config = config_windows
elif platform == 'darwin':
    shutil.copy('Makefile.darwin', 'Makefile')
    config = config_macos
elif platform == 'linux':
    shutil.copy('Makefile.linux', 'Makefile')
    config = config_linux

if config is not None:
    fout = open('Mk.config', 'w')
    fout.write( config() )
    fout.close()
    print("configure.py successful, ready for 'make install'")
