# This workflow manages actions on pull requests and issues

name: daily-pr-and-issue-management

# Run every time a new day starts in the Pacific
on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v3.0.0
      with:
        # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days' # optional
        # The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.
        stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days' # optional
        # The number of days old an issue can be before marking it stale.
        days-before-stale: 60 # optional, default is 60
        # The number of days to wait to close an issue or pull request after it being marked stale. Set to -1 to never close stale issues.
        days-before-close: 7 # optional, default is 7
        # The label to apply when an issue is stale.
        stale-issue-label: stale # optional, default is Stale
        # The labels to apply when an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2")
        exempt-issue-labels: bug # optional, default is 
        # The label to apply when a pull request is stale.
        stale-pr-label: stale # optional, default is Stale
        # The labels to apply when a pull request is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2")
        exempt-pr-labels: bug # optional, default is 
        # Only issues or pull requests with all of these labels are checked if stale. Defaults to `[]` (disabled) and can be a comma-separated list of labels.
        # only-labels: # optional, default is 
        # The maximum number of operations per run, used to control rate limiting.
        # operations-per-run: # optional, default is 30
        # Remove stale labels from issues when they are updated or commented on.
        remove-stale-when-updated: true # optional, default is true
        # Run the processor in debug mode without actually performing any operations on live issues.
        debug-only: true # optional
